---
triple:          'arm64-apple-darwin'
binary-path:     '/Users/mac/workspace/cpp_learn/app'
relocations:
  - { offsetInCU: 0x6111, offset: 0x6111, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x1E330, symBinAddr: 0x100008000, symSize: 0x0 }
  - { offsetInCU: 0x6295, offset: 0x6295, size: 0x8, addend: 0x0, symName: _main, symObjAddr: 0x0, symBinAddr: 0x100003C28, symSize: 0xC0 }
  - { offsetInCU: 0x4778, offset: 0xAA3D, size: 0x8, addend: 0x0, symName: __ZStL8__ioinit, symObjAddr: 0x1DFF0, symBinAddr: 0x100008001, symSize: 0x0 }
  - { offsetInCU: 0x48CC, offset: 0xAB91, size: 0x8, addend: 0x0, symName: __Z8multiplyii, symObjAddr: 0x0, symBinAddr: 0x100003D38, symSize: 0x44 }
...
